version: "3.7"
services:
  nb-tb-connector:
    image: smartcommunitylab/nb-tb-connector:latest
    container_name: nb-tb-connector
    ports:
      - 3030:3030
    env_file:
      - ./nb-tb-connector.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
  tb-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
